# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ExactGPModel": "00_core.ipynb",
         "nv_cost": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://matjesg.github.io/gp_dev/"

git_url = "https://github.com/matjesg/gp_dev/tree/master/"

def custom_doc_links(name): return None
